services:
  frontend:
    restart: always
    build: 
      context: ./frontend
      args: 
      - REACT_APP_API_URL=/api
      - REACT_APP_API_URL=/ws
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
      - REACT_APP_WS_URL=/ws
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
    depends_on:
      - backend
    #networks:
      #- app-network
  backend:
    restart: always
    build: 
      context: ./backend/czat2/  
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8080"
    environment:
      - DB_HOST=um65462-001.eu.clouddb.ovh.net
      - DB_PORT=35791
      - DB_NAME=sexnow
      - DB_USER=sexnow
      - DB_PASSWORD=KluczWiolinowy2024
      - JWT_ISSUER_URI=https://auth.seksnow.pl
      - JWT_JWKS_URI=https://auth.seksnow.pl/.well-known/jwks.json
      - JWT_SECRET=defaultSexNowSecureSecret2025
      - JWT_EXPIRATION_MS=86400000 # 24h
      - JWT_REFRESH_EXPIRATION_MS=604800000 # 7d
      - CORS_ALLOWED_ORIGINS=https://seksnow.pl
      - JWT_EXPIRATION=3600
    #depends_on:
    #  - db
    #networks:
    #  - app-network

      