services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    #environment:
      #- REACT_APP_API_URL=http://backend:8000
    #depends_on:
      #- backend
    #networks:
      #- app-network