spring:
  main:
    allow-bean-definition-overriding: true
  webflux:
    cors:
      allowed-origins: 
        - https://sexnow.pl
        - https://www.sexnow.pl
        - http://localhost:3000
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - KlikId
      exposed-headers:
        - X-Registration-Status
        - X-Email-Verified
      allow-credentials: true
      max-age: 3600

  security:
    filter:
          dispatcher-types: async, request, error
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://auth.sexnow.pl}
          jwk-set-uri: ${JWT_JWKS_URI:https://auth.sexnow.pl/.well-known/jwks.json}

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sexnow}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

jwt:
  secret: ${JWT_SECRET:defaultSexNowSecureSecret2025}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24h
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000} # 7d

security:
  auth:
    registration:
      require-email-verification: true
      allowed-domains:
        - sexnow.pl
        - gmail.com
        - wp.pl

server:
  port: 8080
  ssl:
    enabled: ${ENABLE_SSL:false}
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
    key-password: ${SSL_KEY_PASSWORD}spring:
  main:
    allow-bean-definition-overriding: true


  security:
        filter:
          dispatcher-types: async, request, error

